### ISSUE TITLE
Msgfplus and nonspecific

### ISSUE THREAD

**Issue by cguetot** [ursgal/ursgal#100]
Hi ursgal,

I noted that you have been including new code to deal with nonspecific search.  I am testing it and xtandem and omssa run without any issues so far.  However, I get error message for msgfplus.

 ```
dmpjson  ] Json dumped. Path: /home/ubuntu/projects/lars/msgfplus_v2018_09_12/nonspecific_KristofferS_H1507_195_msgfplus_v2018_09_12.mzid.gz.u.json

        -\-     msgfplus_v2018_09_12 run initialized with nonspecific_KristofferS_H1507_195.mgf (Thu Jan 10 09:36:44 2019)     -/-

[   run    ] Will compress output nonspecific_KristofferS_H1507_195_msgfplus_v2018_09_12.mzid on the fly ... renamed temporarily params["output_file"]
[   run    ] Preparing engine
[   run    ] Starting engine
[ Citation ]
[  Please  ]
[  cite:   ] Kim S, Mischerikow N, Bandeira N, Navarro JD, Wich L, Mohammed S, Heck AJ, Pevzner PA. (2010) The Generating Function of CID, ETD, and CID/ETD Pairs of Tandem Mass Spectra: Applications to Database Search.
[  -----   ]
[ Citation ]
[ PREFLGHT ] Executing preflight sequence ...
[ prefligh ] Execution time 0.000 seconds
[ eXecutio ] Executing command list ...
MS-GF+ Release (v2018.09.12) (12 September 2018)
[Error] Cannot specify a MaxMissedCleavages when using unspecific cleavage enzyme

Traceback (most recent call last):
  File "/home/ubuntu/repos/ursgal_dda/nonspecific_run.py", line 116, in <module>
    search_engine=SEARCH_ENGINE
  File "/home/ubuntu/repos/ursgal_dda/nonspecific_run.py", line 65, in main
    engine=search_engine,
  File "/usr/local/lib/python3.6/dist-packages/ursgal/ucontroller.py", line 1856, in search
    force      = force,
  File "/usr/local/lib/python3.6/dist-packages/ursgal/ucontroller.py", line 1766, in search_mgf
    force, engine_name, answer
  File "/usr/local/lib/python3.6/dist-packages/ursgal/ucontroller.py", line 2186, in run_unode_if_required
    json_path = json_path,
  File "/usr/local/lib/python3.6/dist-packages/ursgal/unode.py", line 1400, in run
    report['execution'] = self._execute()
  File "/usr/local/lib/python3.6/dist-packages/ursgal/unode.py", line 485, in _execute
    '''.format( self.engine, os.path.relpath(self.exe), self.execute_return_code)
AssertionError:

msgfplus_v2018_09_12 crashed!

  The executable
    ../../../../usr/local/lib/python3.6/dist-packages/ursgal/resources/platform_independent/arc_independent/msgfplus_v2018_09_12/MSGFPlus.jar
  terminated with Error code 255 .
  Inspect the printouts above for possible causes and verify that all input files are valid.


```

**Comment by StSchulze** [comment]
According to your printout
`[Error] Cannot specify a MaxMissedCleavages when using unspecific cleavage enzyme`
the problem is that MSGF+ does not allow to specify a maximum number of missed cleavages when using unspecific cleavage.
Have you tried setting it to None or is it required to not set the flag (-maxMissedCleavages) at all (you should be able to try that by just commenting out your msgfplus version in "available_in_unode" for "max_missed_cleavages"?
I will have a look at it as well as soon as possible.

**Comment by cguetot** [comment]
> According to your printout
> `[Error] Cannot specify a MaxMissedCleavages when using unspecific cleavage enzyme`
> the problem is that MSGF+ does not allow to specify a maximum number of missed cleavages when using unspecific cleavage.
> Have you tried setting it to None or is it required to not set the flag (-maxMissedCleavages) at all (you should be able to try that by just commenting out your msgfplus version in "available_in_unode" for "max_missed_cleavages"?
> I will have a look at it as well as soon as possible.

Thanks for your reply. Neither options works.  However, reading the msgfplus docs, it looks the issue disappear after setting params['max_missed_cleavages'] to -1.

**Comment by StSchulze** [comment]
Great, thanks for checking that.
I forgot to mention that, in general, we don't check if a certain combination of parameters is allowed or makes sense, since this would be quite some work for the different engines and use cases.
But we will include you case in the FAQs to have it documented here as well ;)
