### ISSUE TITLE
error while downloading percolator 3_2_1

### ISSUE THREAD

**Issue by cguetot** [ursgal/ursgal#108]
Hi guys, 

I am trying to upgrade ursgal to version 0.6.3. However, something happens when it try to install the resources.

Executable for percolator_3_2_1 is not available on your system
[ -<HTPP>- ] Downloading files from https://www.sas.upenn.edu/~sschulze/ursgal_resources/ursgal/resources/linux/64bit/percolator_3_2_1/percolator_3_2_1.md ...
[ -<HTPP>- ] 	 WARNING! Could not download https://www.sas.upenn.edu/~sschulze/ursgal_resources/ursgal/resources/linux/64bit/percolator_3_2_1/percolator_3_2_1.md Check your internet connection! [ -<HTPP>- ] For OSX, make sure that certificates are installed (Applications/Python 3.x/Install Certificates.command)
Traceback (most recent call last):
  File "install_resources.py", line 40, in <module>
    main(resources)
  File "install_resources.py", line 13, in main
    downloaded_zips = uc.download_resources( resources = resources)
  File "/home/carlos/projects/epigg/containers/test_ursgal/ursgal/ursgal/ucontroller.py", line 2763, in download_resources
    'r'
FileNotFoundError: [Errno 2] No such file or directory: '/home/carlos/projects/epigg/containers/test_ursgal/ursgal/ursgal/resources/linux/64bit/percolator_3_2_1/percolator_3_2_1.md'

**Comment by StSchulze** [comment]
Hi Carlos,

I'm sorry, we wanted to distribute Percolator 3.2.1 the same way as 2.08, i.e. through install_resources, but we had problems to compile it/get the standalone for all systems. For now, it needs to be downloaded manually from: https://github.com/percolator/percolator/releases

The failing install_resources should be fixed now.

**Comment by cguetot** [comment]
tack så mycket!
