### ISSUE TITLE
2 test failures on windows 8

### ISSUE THREAD

**Issue by wolski** [ursgal/ursgal#11]
Platform Windows 8.
C:\Users\wolski\prog\ursgal>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32

Running:

C:\Users\wolski\prog\ursgal>nosetests --version
nosetests version 1.3.7

Produces the following 2 test failures.

Even with those 2 errors ursgal looks super cool (especially all those great examples) and I will dedicate it some time before Christmas on windows and Linux.

.............................................................................................................................................
.
======================================================================
FAIL: calc_md5_test.check_md5_test({'input': 'tests\\data\\test.json', 'output': '379450895e2c116886b2e92dfcd68b2b'},)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\wolski\appdata\local\programs\python\python35\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\wolski\prog\ursgal\tests\calc_md5_test.py", line 33, in check_md5
    out_put
AssertionError:
        MD5 {'input': 'tests\\data\\test.json', 'output': '379450895e2c116886b2e92dfcd68b2b'} failed
        output: 54c19ed069413037dc857a0130dd2527
-------------------- >> begin captured stdout << ---------------------
[ ucontrol ] Calculating md5 for test.json ....
54c19ed069413037dc857a0130dd2527 {'input': 'tests\\data\\test.json', 'output': '379450895e2c116886b2e92dfcd68b2b'}

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: calc_md5_test.check_md5_test({'input': 'tests\\data\\test_without_database.json', 'output': 'deb20d01ff369188a583decf203cf769'},)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\wolski\appdata\local\programs\python\python35\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\wolski\prog\ursgal\tests\calc_md5_test.py", line 33, in check_md5
    out_put
AssertionError:
        MD5 {'input': 'tests\\data\\test_without_database.json', 'output': 'deb20d01ff369188a583decf203cf769'} failed
        output: 26cc3e0850d3ab95c74e4cf680475335
-------------------- >> begin captured stdout << ---------------------
[ ucontrol ] Calculating md5 for test_without_database.json ....
26cc3e0850d3ab95c74e4cf680475335 {'input': 'tests\\data\\test_without_database.json', 'output': 'deb20d01ff369188a583decf203cf769'}

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------

**Comment by StSchulze** [comment]
The md5 calculation somehow differs between Windows 8 (and above) and all other systems. However, it is consistent within Windows 8/10, so you should not have any problems with jsons you create on your system.

So we are aware of this issue in the tests but could not solve it yet.

**Comment by wolski** [comment]
Did you check if the change in the md5 sum on windows is due to different line endings introduced?

**Comment by JB-MS** [comment]
The line endings are indeed the problem. The respective test was adjusted to handle md5 calculation with win32 line endings. However, depending on the git settings line endings are converted or not. So this solution might not work on all setups. Maybe you check out the new version, try it and let me know if everything works.

**Comment by StSchulze** [comment]
Works on Windos 10 here, nice!

**Comment by JB-MS** [comment]
Can this be closed now? Is the issue still present on Windows 8?
