### ISSUE TITLE
Modules not passing engine_sanity_check

### ISSUE THREAD

**Issue by realperson999** [ursgal/ursgal#110]
Some of the example scripts seems to not be passing the engine_sanity_check.

From simple_combined_fdr_score.py:

```
C:\Base\ursgal\example_scripts>python simple_combined_fdr_score.py

        -\-     UController initialized (Fri Mar 29 13:17:14 2019)     -/-
         -\-    Ursgal v0.6.3  -  https://github.com/ursgal/ursgal    -/-

[ profile  ] Initializing profile LTQ XL low res
[ profile  ] 4 parameters have been updated

Traceback (most recent call last):
  File "simple_combined_fdr_score.py", line 103, in <module>
    main()
  File "simple_combined_fdr_score.py", line 71, in main
    engine='get_ftp_files_1_0_0'
  File "C:\Python37\lib\site-packages\ursgal\ucontroller.py", line 563, in fetch_file
    engine     = engine,
  File "C:\Python37\lib\site-packages\ursgal\ucontroller.py", line 2916, in execute_unode
    engine_name = self.engine_sanity_check( engine )
  File "C:\Python37\lib\site-packages\ursgal\ucontroller.py", line 512, in engine_sanity_check
    '''.format( short_engine )
AssertionError:
      The engine name "get_ftp_files_1_0_0" you have specified was not found.
      Make sure that you spelled it correctly!
```

I get similar output from other example scripts, usually things in the misc engine don't pass the sanity check. However I do seem to have all of these components installed, they come up as available when I run install_resources.py (ursgal.UController() doesn't show the full list of what's available anymore?), and the files are present in the correct folders. Nosetests doesn't show any issues.

An example of something I can get to work is target_decoy_generation_example.py. This seems to have the same problem, involving generate_target_decoy_1_0_0 not passing engine_sanity_check, but I was able to run generate_target_decoy_1_0_0 to generate a decoy fasta file just fine.

**Comment by StSchulze** [comment]
Hi  realperson999,

Thanks for using Ursgal and reporting problems.
Unfortunately, I am not able to reproduce you error.
I have tried it on a Windows as well as a Unix machine and tried it with Ursgal being installed to the site-packages as well as just being linked to the folder.

ursgal.UController()  also still shows the list of available engines for me.

So I'm not sure what's happening and maybe one of the other developers can confirm/reproduce the error.
But my guess would be that something went wrong with the installation on your side.
Did you use setup.py to install it to the site-packages or did you just link the folder?

Best,
Stefan

**Comment by realperson999** [comment]
I removed everything and re-did the install, seems to be working now. I should've done that first, sorry ^_^

**Comment by StSchulze** [comment]
No worries, glad it works ;)
