### ISSUE TITLE
Delete obsolete branches

### ISSUE THREAD

**Issue by MKoesters** [ursgal/ursgal#119]
Since we have a lot of branches, which either have been merged or will not be merged but are still in the main repo, we should delete the ones which we do not need anymore.

I'd suggest to delete the following branches:

- MKoesters-percolator3
- alt_docu_trigger
- fix_mp
- hotfix/m_double_mods_on1
- pypi_badge
- upstream/master
- venn_1_1_0

these branches are all merged, so we are not loosing anything

What about the format/black branch?
git tells me that this branch has not been merged yet

Best,
Manuel

**Comment by StSchulze** [comment]
Deleting the listed ones sounds perfect to me.

Yeah, the foramt/black branch is not merged yet. I think the idea was that the fufezan_lab account does it in order to keep contributions somewhat appropriate, but I wouldn't mind either way.

**Comment by JB-MS** [comment]
We can delete the old branches.

However, I would prefer that the lab bot commits the changes.

Cheers,
Joe

**Comment by MKoesters** [comment]
Deleting branches does not change the commit history, afaik.
So it should not really matter, who deletes the branches

**Comment by JB-MS** [comment]
I was referring to the format/black commit, which will be huge. A job for the lab bot :)

**Comment by MKoesters** [comment]
Ups, did not read the comment before, but yeah, definitely a job for the lab bot

**Comment by MKoesters** [comment]
All obsolete branches should be deleted now :)
