### ISSUE TITLE
Could not load RT lookup dict from this location: 

### ISSUE THREAD

**Issue by wolski** [ursgal/ursgal#12]
Windows 8. Did run into the following problem:
Could not load RT lookup dict from this location: 
D:\projects\p2069\dataSearchResults\mgf\GRAY_HD\_ursgal_lookup.pkl

Indeed there is no pkl file at this location.

Please find below the complete console output.

C:\Users\wolski\AppData\Local\Programs\Python\Python35\python.exe "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.1\helpers\pydev\pydevd.py" --multiproc --qt-support --client 127.0.0.1 --port 64812 --file C:/Users/wolski/prog/ursgal/example_scripts/do_it_all_folder_wide.py
pydev debugger: process 5004 is connecting

Connected to pydev debugger (build 163.9735.8)

        -\-     UController initialized (Thu Dec 15 11:52:37 2016)     -/-
         -\-    Ursgal v0.4.0  -  https://github.com/ursgal/ursgal    -/-

[ ucontrol ] Initializing profile QExactive+
[ ucontrol ] 4 parameters have been updated
[ WARNING! ] Engine msamanda_1_0_0_5242 is not available in C:\Users\wolski\prog\ursgal\ursgal\resources\win32\64bit\msamanda_1_0_0_5242
[ WARNING! ] Engine msamanda_1_0_0_6299 is not available in C:\Users\wolski\prog\ursgal\ursgal\resources\win32\64bit\msamanda_1_0_0_6299
[ WARNING! ] Engine msamanda_1_0_0_7503 is not available in C:\Users\wolski\prog\ursgal\ursgal\resources\win32\64bit\msamanda_1_0_0_7503
[ WARNING! ] Engine novor_1_1beta is not available in C:\Users\wolski\prog\ursgal\ursgal\resources\win32\64bit\novor_1_1beta
[ WARNING! ] Engine pepnovo_3_1 is not available in C:\Users\wolski\prog\ursgal\ursgal\resources\win32\64bit\pepnovo_3_1

	CONVERTER(s):
	  0 : add_estimated_fdr_1_0_0      [         available         ] 
	  1 : filter_csv_1_0_0             [         available         ] 
	  2 : generate_target_decoy_1_0_0  [         available         ] 
	  3 : merge_csvs_1_0_0             [         available         ] 
	  4 : msgfplus2csv_v2016_09_16     [         available         ] 
	  5 : mzidentml_lib_1_6_10         [         available         ] 
	  6 : mzidentml_lib_1_6_11         [         available         ] 
	  7 : mzml2mgf_1_0_0               [         available         ] 
	  8 : sanitize_csv_1_0_0           [         available         ] 
	  9 : xtandem2csv_1_0_0            [         available         ] 
	DENOVO_ENGINE(s):
	 10 : novor_1_1beta                [       cant find exe       ] 
	 11 : pepnovo_3_1                  [       cant find exe       ] 
	FETCHER(s):
	 12 : get_http_files_1_0_0         [         available         ] 
	META_ENGINE(s):
	 13 : combine_FDR_0_1              [         available         ] 
	 14 : combine_pep_1_0_0            [         available         ] 
	 15 : naive_bayes_1_0_0            [         available         ] 
	SEARCH_ENGINE(s):
	 16 : msamanda_1_0_0_5242          [       cant find exe       ] 
	 17 : msamanda_1_0_0_5243          [            n/d            ] 
	 18 : msamanda_1_0_0_6299          [       cant find exe       ] 
	 19 : msamanda_1_0_0_6300          [            n/d            ] 
	 20 : msamanda_1_0_0_7503          [       cant find exe       ] 
	 21 : msamanda_1_0_0_7504          [            n/d            ] 
	 22 : msgfplus_v2016_09_16         [         available         ] 
	 23 : msgfplus_v9979               [         available         ] 
	 24 : myrimatch_2_1_138            [            n/d            ] 
	 25 : myrimatch_2_2_140            [         available         ] 
	 26 : omssa_2_1_9                  [         available         ] 
	 27 : xtandem_cyclone_2010         [         available         ] 
	 28 : xtandem_jackhammer           [         available         ] 
	 29 : xtandem_piledriver           [         available         ] 
	 30 : xtandem_sledgehammer         [         available         ] 
	 31 : xtandem_vengeance            [         available         ] 
	VALIDATION_ENGINE(s):
	 32 : percolator_2_08              [         available         ] 
	 33 : qvality_2_02                 [         available         ] 
	VISUALIZER(s):
	 34 : venndiagram_1_0_0            [         available         ] 
[ ucontrol ] Initializing profile QExactive+
[ ucontrol ] 4 parameters have been updated
[ ucontrol ] Preparing unode run for engine xtandem_vengeance on file(s) D:/projects/p2069/dataSearchResults/mgf/GRAY_HD\20160704_03_C_01.mgf
[ ucontrol ] Setting self.io["input"]
[ ucontrol ] Generated engine xtandem_vengeance output file name: D:\projects\p2069\dataSearchResults\mgf\GRAY_HD\xtandem_vengeance\20160704_03_C_01_xtandem_vengeance.xml.gz
[ ucontrol ] search_mgf() scheduled on input file 20160704_03_C_01.mgf
[ ucontrol ] Reason for run: Never executed before. No out_json 20160704_03_C_01_xtandem_vengeance.xml.gz.u.json found.
[ ucontrol ] Preparing json dump
[ ucontrol ] Json dumped. Path: D:\projects\p2069\dataSearchResults\mgf\GRAY_HD\xtandem_vengeance\20160704_03_C_01_xtandem_vengeance.xml.gz.u.json

        -\-     xtandem_vengeance run initialized with 20160704_03_C_01.mgf (Thu Dec 15 11:52:37 2016)     -/-

[ xtandem_ ] Will compress output 20160704_03_C_01_xtandem_vengeance.xml on the fly ... renamed temporarily params["output_file"]
[ xtandem_ ] Preparing engine
[ xtandem_ ] Starting engine
[          ] 
[  Please  ] 
[  cite:   ] Craig R, Beavis RC. (2004) TANDEM: matching proteins with tandem mass spectra.
[  -----   ] 
[          ] 
[ PREFLGHT ] Executing preflight sequence ...
[ xtandem_ ] wrote input file taxonomy.xml
[ xtandem_ ] wrote input file default_input.xml
[ xtandem_ ] wrote input file input.xml
[ prefligh ] Execution time 0.00 seconds
[ eXecutio ] Executing command list ...

X! TANDEM Vengeance (2015.12.15.2)

Loading spectra| (mgf)............... loaded.
Spectra matching criteria = 27889
Starting threads .|.|.|.|.|.|.|.|.|.|. started.
Computing models:
S
waiting for 234|5|6|7|8|9|10|11| done.

sequences modelled = 41 ks
Model refinement:

waiting for 2|3|4|5|6|7|8|9|10|11| done.

Merging results:
from 2..3..4..5..6..7..8..9..10..11..

Creating report:
initial calculations  ..... done.
sorting  ..... done.
finding repeats ..... done.
evaluating results ..... done.
calculating expectations ..... done.
writing results ..... done.

Valid models = 12517

[ executio ] Execution time 1.63 minutes
[ POSTFLGH ] Executing postflight sequence ...
[ postflig ] Execution time 0.00 seconds
[ xtandem_ ] Compressing output 20160704_03_C_01_xtandem_vengeance.xml > 20160704_03_C_01_xtandem_vengeance.xml.gz
[   run    ] Execution time 2.20 minutes
[ ucontrol ] Preparing json dump
[ ucontrol ] Calculating md5 for 20160704_03_C_01_xtandem_vengeance.xml.gz ....
[ ucontrol ] Json dumped. Path: D:\projects\p2069\dataSearchResults\mgf\GRAY_HD\xtandem_vengeance\20160704_03_C_01_xtandem_vengeance.xml.gz.u.json
[ ucontrol ] Initializing profile QExactive+
[ ucontrol ] 4 parameters have been updated
[ ucontrol ] Preparing unode run for engine xtandem2csv_1_0_0 on file(s) D:\projects\p2069\dataSearchResults\mgf\GRAY_HD\xtandem_vengeance\20160704_03_C_01_xtandem_vengeance.xml.gz
[ ucontrol ] Setting self.io["input"]
[ ucontrol ] Generated engine xtandem2csv_1_0_0 output file name: D:\projects\p2069\dataSearchResults\mgf\GRAY_HD\xtandem_vengeance\20160704_03_C_01_xtandem_vengeance.csv
[ ucontrol ] execute_unode() scheduled on input file 20160704_03_C_01_xtandem_vengeance.xml.gz
[ ucontrol ] Reason for run: Never executed before. No out_json 20160704_03_C_01_xtandem_vengeance.csv.u.json found.
[ ucontrol ] Preparing json dump
[ ucontrol ] Json dumped. Path: D:\projects\p2069\dataSearchResults\mgf\GRAY_HD\xtandem_vengeance\20160704_03_C_01_xtandem_vengeance.csv.u.json

        -\-     xtandem2csv_1_0_0 run initialized with 20160704_03_C_01_xtandem_vengeance.xml.gz (Thu Dec 15 11:54:49 2016)     -/-

[ xtandem2 ] Preparing engine
[ xtandem2 ] Starting engine
[ PREFLGHT ] Executing preflight sequence ...
[ prefligh ] Execution time 0.00 seconds
[ -ENGINE- ] Executing conversion ..
Converting XTandem XML into CSV: D:\projects\p2069\dataSearchResults\mgf\GRAY_HD\xtandem_vengeance\20160704_03_C_01_xtandem_vengeance.xml.gz
[ executio ] Execution time 1.63 minutes
[ POSTFLGH ] Executing postflight sequence ...
[ postflig ] Execution time 0.00 seconds
[   run    ] Execution time 2.20 minutes
[ ucontrol ] Preparing json dump
[ ucontrol ] Calculating md5 for 20160704_03_C_01_xtandem_vengeance.csv ....
[ ucontrol ] Json dumped. Path: D:\projects\p2069\dataSearchResults\mgf\GRAY_HD\xtandem_vengeance\20160704_03_C_01_xtandem_vengeance.csv.u.json
[ ucontrol ] Initializing profile QExactive+
[ ucontrol ] 4 parameters have been updated
[ ucontrol ] Preparing unode run for engine unify_csv_1_0_0 on file(s) D:\projects\p2069\dataSearchResults\mgf\GRAY_HD\xtandem_vengeance\20160704_03_C_01_xtandem_vengeance.csv
[ ucontrol ] Setting self.io["input"]
[ ucontrol ] Generated engine unify_csv_1_0_0 output file name: D:\projects\p2069\dataSearchResults\mgf\GRAY_HD\xtandem_vengeance\20160704_03_C_01_xtandem_vengeance_unified.csv
[ ucontrol ] execute_unode() scheduled on input file 20160704_03_C_01_xtandem_vengeance.csv
[ ucontrol ] Reason for run: Never executed before. No out_json 20160704_03_C_01_xtandem_vengeance_unified.csv.u.json found.
[ ucontrol ] Preparing json dump
[ ucontrol ] Json dumped. Path: D:\projects\p2069\dataSearchResults\mgf\GRAY_HD\xtandem_vengeance\20160704_03_C_01_xtandem_vengeance_unified.csv.u.json

        -\-     unify_csv_1_0_0 run initialized with 20160704_03_C_01_xtandem_vengeance.csv (Thu Dec 15 11:55:17 2016)     -/-

[ unify_cs ] Preparing engine
[ unify_cs ] Starting engine
[          ] 
[  Please  ] 
[  cite:   ] Kremer, L. P. M., Leufken, J., Oyunchimeg, P., Schulze, S. & Fufezan, C. (2016) Ursgal, Universal Python Module Combining Common Bottom-Up Proteomics Tools for Large-Scale Analysis. J. Proteome res. 15, 788-794.
[  -----   ] 
[          ] 
[ PREFLGHT ] Executing preflight sequence ...
[ prefligh ] Execution time 0.00 seconds
[ -ENGINE- ] Executing conversion ..
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.1\helpers\pydev\pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.1\helpers\pydev\pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/wolski/prog/ursgal/example_scripts/do_it_all_folder_wide.py", line 125, in <module>
    target_decoy_database = "D:/projects/p2069/dataSearchResults/fasta/p2069_db1_d_20160322.fasta"
  File "C:/Users/wolski/prog/ursgal/example_scripts/do_it_all_folder_wide.py", line 97, in main
    engine     = search_engine,
  File "C:\Users\wolski\prog\ursgal\ursgal\ucontroller.py", line 1843, in search
    force            = force,
  File "C:\Users\wolski\prog\ursgal\ursgal\ucontroller.py", line 2150, in unify_csv
    output_file_name = output_file_name
  File "C:\Users\wolski\prog\ursgal\ursgal\ucontroller.py", line 2744, in execute_unode
    force, engine_name, answer
  File "C:\Users\wolski\prog\ursgal\ursgal\ucontroller.py", line 2068, in run_unode_if_required
    json_path = json_path,
  File "C:\Users\wolski\prog\ursgal\ursgal\unode.py", line 1243, in run
    report['execution'] = self._execute()
  File "C:\Users\wolski\prog\ursgal\ursgal\wrappers\unify_csv_1_0_0.py", line 68, in _execute
    """.format( scan_rt_lookup_path )
AssertionError: 
Could not load RT lookup dict from this location: D:\projects\p2069\dataSearchResults\mgf\GRAY_HD\_ursgal_lookup.pkl

**Comment by StSchulze** [comment]
Hi,
thanks for the report.
The RT lookup pkl is created during mzml to mgf conversion. So two questions for the understanding of the problem:
Did you use mzml files for the pipeline? Did any problems occur during the conversion?

**Comment by wolski** [comment]
No, I do not use the mzml files. I pass a directory wich contains mgf files to  do_it_all_folder.py

In addition I modified line 
31 in do_it_all_folder.py to read like:
for mzml in glob.glob(os.path.join('{0}'.format(folder),'*.mgf')):

**Comment by StSchulze** [comment]
We have designed the pipeline to be used with mzml files since it is the HUPO standard.
You can use search_mgf with mgf files but unify_csv (and therefore a lot of engines that need unified csv files) will not work, so using mzml files is probably the better option.

**Comment by wolski** [comment]
May I ask you a favor please!? Can we stick to the technical details.

What is the mgf.u.json file for and who is generating it?
 Is it needed by do_it_all_folder_wide.py?

If I am correct the _ursgal_lookup.pkl contains 

{FILENAME = {rt_2_scan={time = scan, ...},scan_2_rt={scan=rt,...}, unit='seconds'}}

Are some other files generated during the file conversion from mzML.

**Comment by StSchulze** [comment]
The general use of the u.json files is explained in the documentation (Quick Start Tutorial --> 6.JSONs, Force and File Names and also the general structure figure b), so ursgal is generating a json for each node that is executed and therefore it is also needed for the workflow, yes.

Regarding the _ursgal_lookup.pkl you are right.

The mzml2mgf converter generates the .mgf file, the lookup pkl and the mgf.u.json, that's it.

**Comment by wolski** [comment]
Thanks. I wish there would be better support for mgf files if the information in those files is sufficient which seems to be the case.  I close the issue.
