### ISSUE TITLE
Add custom exceptions

### ISSUE THREAD

**Issue by MKoesters** [ursgal/ursgal#120]
Old text:

> When running upeptide_mapper_1_0_0 with an empty input file, it crashes with the following error:
> 
> > File "/home/manuel/Gits/Ursgal/ursgal_fork2/ursgal/resources/platform_independent/arc_independent/upeptide_mapper_1_0_0/upeptide_mapper_1_0_0.py", line 234, in main
>     *class_etxra_args
>   File "/home/manuel/Gits/Ursgal/ursgal_fork2/ursgal/resources/platform_independent/arc_independent/upeptide_mapper_1_0_0/upeptide_mapper_1_0_0.py", line 776, in map_peptides
>     for match in self.automatons[fasta_name].iter(self.total_sequence_string[fasta_name]):
> AttributeError: Not an Aho-Corasick automaton yet: call add_word to add some keys and call make_automaton to convert the trie to an automaton.
> 
> I'd suggest to just return an empty output file and maybe print a warning, since this could crash e.g. a machine offset sweep workflow otherwise

New:

In order to handle the above mentioned issue, we agreed to implement ursgal specific exceptions, for e.g. empty files, so we can handle these exceptions in try/except statements so we don't need to fallback on accepting e.g. AttributeErrors, which could also occur due to different reasons.

Best,
Manuel

**Comment by StSchulze** [comment]
I had that problem before as well and as a work around I put it in a try/except loop for e.g. the parameter sweep workflow. For this type of workflow just allowing the upeptide mapper to pass also would let percolator crash afterwards, so that would need to be solved then as well.

However, I would like it to crash in other workflows to know that something is wrong.
But I guess we could work on exit messages/error messages to deal with this?

**Comment by MKoesters** [comment]
I personally prefer the option to also make percolator accept empty files, however I see that this would mean pulling this through for every node and also that there are other valid opinions on that.

I also fixed that with a try/except condition for now, however you need to accept all AttributeErrors, which could also be something completely different, especially in such a big node.
If we agree on raising an Error, I'd like to have something escape an `UrsgalError` or something similar.
If we agree on this, I'd add a custom exception which will also be useful in future I think ( I know we had some discussions on custom erros, still a big fan of this concept :) )

Best,
Manuel

**Comment by JB-MS** [comment]
I also like the idea of having an `UsrgalError` or more specific errors for different cases.  This could then be well implemented in a workflow and handling these errors specifically, like having no peptides to process etc.

**Comment by MKoesters** [comment]
I can add a new exceptions.py file with a general `UrsgalError` and a `NoPeptidesToMap` error (or similar) and fix this specific case.
In future, we could inherit other errors from `UrsgalError` for other  cases.

**Comment by StSchulze** [comment]
Yes, sounds good to me

**Comment by MKoesters** [comment]
Just made a draft, please have a look if you like it.
The names of the exceptions are open for discussion (best directly in the PR), as well as the location of the tests for these custom exceptions

**Comment by StSchulze** [comment]
Agreement from dev meeting:
Instead of generating Ursgal exceptions we will use built-in exceptions to cover empty files and potentially other cases.
Ideally we can discuss here, which cases should be covered, if it should be done on wrapper and/or node and/or controller level, and which exceptions should be used for which cases.

**Comment by MKoesters** [comment]
What about ValueError for empty files?

> exception ValueError
> Raised when an operation or function receives an argument that has the right type but an inappropriate value, and the situation is not described by a more precise exception such as IndexError.

One could argue that the passed path has the right type (str) but points to an empty file, which could be interpreted as an inappropriate value.
I could not find anything else which seemed suitable in my opinion.

**Comment by StSchulze** [comment]
What about this one:

> exception EOFError
>     Raised when the input() function hits an end-of-file condition (EOF) without reading any data. (N.B.: the io.IOBase.read() and io.IOBase.readline() methods return an empty string when they hit EOF.)

I would argue that's a bit more specific to he actual problem.

I mean, the ValueError would fit as well, but in terms of usability, it seems to me like ValueErrors might happen more often and at a lot of different places, so skipping them would be fairly dangerous.

**Comment by JB-MS** [comment]
I would prefer the EOFError as well. Seems like the best fitting case for empty files in my opinion.

**Comment by MKoesters** [comment]
Ok, I missed that one but I totaly agree that EOF is more suitable :+1:
