### ISSUE TITLE
problem running myrimatch - Windows 8

### ISSUE THREAD

**Issue by wolski** [ursgal/ursgal#14]
I am getting the following error when executing do_it_all_folder_wide.py example.

ValueError: path is on mount 'D:', start on mount 'C:' 
What does that error mean? Should the data be on the C: drive?

Thanks
Witold

[ ucontrol ] Initializing profile QExactive+
[ ucontrol ] 4 parameters have been updated
[ ucontrol ] Preparing unode run for engine myrimatch_2_2_140 on file(s) D:\projects\p2069\dataSearchResults\mzML\20160704_03_C_01.mgf
[ ucontrol ] Setting self.io["input"]
[ ucontrol ] Generated engine myrimatch_2_2_140 output file name: D:\projects\p2069\dataSearchResults\mzML\myrimatch_2_2_140\20160704_03_C_01_myrimatch_2_2_140.mzid.gz
[ ucontrol ] search_mgf() scheduled on input file 20160704_03_C_01.mgf
[ ucontrol ] Reason for run: Never executed before. No out_json 20160704_03_C_01_myrimatch_2_2_140.mzid.gz.u.json found.
[ ucontrol ] Preparing json dump
[ ucontrol ] Json dumped. Path: D:\projects\p2069\dataSearchResults\mzML\myrimatch_2_2_140\20160704_03_C_01_myrimatch_2_2_140.mzid.gz.u.json

Traceback (most recent call last):
        -\-     myrimatch_2_2_140 run initialized with 20160704_03_C_01.mgf (Fri Dec 16 14:02:54 2016)     -/-
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.1\helpers\pydev\pydevd.py", line 1596, in <module>

    globals = debugger.run(setup['file'], None, None, is_module)
[ myrimatc ] Will compress output 20160704_03_C_01_myrimatch_2_2_140.mzid on the fly ... renamed temporarily params["output_file"]
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.1\helpers\pydev\pydevd.py", line 974, in run
[ myrimatc ] Preparing engine
    pydev_imports.execfile(file, globals, locals)  # execute the script
[ myrimatc ] Starting engine
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
[          ] 
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
[  Please  ] 
  File "C:/Users/wolski/prog/ursgal_examples/do_it_all_folder_wide.py", line 126, in <module>
[  cite:   ] Tabb DL, Fernando CG, Chambers MC. (2007) MyriMatch: highly accurate tandem mass spectral peptide identification by multivariate hypergeometric analysis.
    target_decoy_database = "D:/projects/p2069/dataSearchResults/fasta/p2069_db1_d_20160322.fasta"
[  -----   ] 
  File "C:/Users/wolski/prog/ursgal_examples/do_it_all_folder_wide.py", line 98, in main
[          ] 
    engine     = search_engine,
[ PREFLGHT ] Executing preflight sequence ...
  File "C:\Users\wolski\prog\ursgal2\ursgal\ucontroller.py", line 1831, in search
    force      = force,
  File "C:\Users\wolski\prog\ursgal2\ursgal\ucontroller.py", line 1746, in search_mgf
    force, engine_name, answer
  File "C:\Users\wolski\prog\ursgal2\ursgal\ucontroller.py", line 2071, in run_unode_if_required
    json_path = json_path,
  File "C:\Users\wolski\prog\ursgal2\ursgal\unode.py", line 1242, in run
    report['preflight'] = self._preflight()
  File "C:\Users\wolski\prog\ursgal2\ursgal\unode.py", line 988, in _preflight
    preflight_answer = self.preflight()
  File "C:\Users\wolski\prog\ursgal2\ursgal\wrappers\myrimatch_2_1_138.py", line 65, in preflight
    ).format( os.path.relpath(self.params['translations']['mzml_input_file']) ),
  File "C:\Users\wolski\AppData\Local\Programs\Python\Python35\lib\ntpath.py", line 574, in relpath
    path_drive, start_drive))
ValueError: path is on mount 'D:', start on mount 'C:'

Process finished with exit code 1

**Comment by StSchulze** [comment]
I have seen this error on a few windows machines. However, I couldn't figure out a reason for it, since it works on other machines without problems, even on external drives. So it's probably related to some settings in Windows.
But so far it always worked when the data are on the same drive, so in your case putting them on the C drive should help. It's not a nice workaround, though ...

**Comment by wolski** [comment]
Thanks.

According to the second linke below  "....find a relative path between 2 directories and they do not exist (since they are on different drives)."
What makes me wonder is that this error only occurs with the myrimatch search engine. So what might be the difference between the calling code for myrimatch and xtandem or msgf?

I will first try to define the working directory for ursgal on the same drive the data is on. Hope this works.


http://stackoverflow.com/questions/32804421/valueerror-path-is-on-drive-c-start-on-drive-d
http://stackoverflow.com/questions/40448938/valueerror-path-is-on-mount-c-start-on-mount-f-while-django-migrations-i

**Comment by StSchulze** [comment]
Glad to hear that it works on the same drive.

I replaced relpath in the myrimatch wrapper. Since it doesn't occur in the other engines, it could be the reason. Let me know if it works (unfortunately I cannot test it right now ...).
