### ISSUE TITLE
ERROR: coverage

### ISSUE THREAD

**Issue by Deanho** [ursgal/ursgal#166]
Hi,
Running 'tox' tests, I get the following error from 'coverage':

 py37: commands succeeded
ERROR:   coverage: commands failed
 docu: commands succeeded
 example_scripts: commands succeeded

Any ideas what is wrong with my installation?
I'm in Windows 8.1 64-bit. Python Anaconda installation. The same thing happens in Windows 10 too.
Is it just a "path to coverage" issue?
Regards,
Dean

**Comment by MKoesters** [comment]
Hi @Deanho,

Thanks for using ursgal!
The coverage is mainly aimed at ursgal developers to check if the code they want to contribute is actually tested.
Even with this failing, you can use ursgal without any problems as long as py37 and example scripts are succeeding!

If you anyways want to fix this, could you please copy the full error here and the command you execute?
This would make it a lot more easier for me to help you
Also, could you tell me which python version you are using (simply type python --version in the terminal)?

Best,
Manuel

**Comment by MKoesters** [comment]
I closed this since I was not hearing back and I cant reproduce the error.
If the error is still occuring, feel free to reopen this issue.

Best,
Manuel
