### ISSUE TITLE
issue with TMT modifications & OMSSA

### ISSUE THREAD

**Issue by tobymathieson** [ursgal/ursgal#17]
Hi there, 
I wanted to use Ursgal to search TMT modifications on any Ntermini and as fixed modification on K. 

I adapted the all_mods as follows:

        'K,fix,any,TMT6plex',
        '*,opt,N-term,TMT6plex',

But I get this error when Ursgal starts OMSSA (it works with most of the other search engines):

[ WARNING  ]
    The combination of modification name and aminoacid is not supported by
    OMSSA. Continuing without modification: {'id': '737', 'org': 'K,fix,any,TMT6plex', 'name': 'TMT6plex', 'composition': {'O': 2, 'N': 1, '15N': 1, '13C': 4, 'C': 8, 'H': 20}, 'mass': 229.162932, 'unimod': True, 'aa': 'K', '_id': 3, 'pos': 'any'}

[ WARNING  ]
    The combination of modification name and aminoacid is not supported by
    OMSSA. Continuing without modification: {'id': '737', 'org': '*,opt,N-term,TMT6plex', 'name': 'TMT6plex', 'composition': {'O': 2, 'N': 1, '15N': 1, '13C': 4, 'C': 8, 'H': 20}, 'mass': 229.162932, 'unimod': True, 'aa': '*', '_id': 0, 'pos': 'N-term'}

If I look in the OMSSA mods.xml file, TMT is there but has slightly different names:

<MSModSpec_name>TMT 6-plex on n-term peptide</MSModSpec_name>

<MSModSpec_name>TMT 6-plex on K</MSModSpec_name>

Any help gratefully received!
Toby

**Comment by JB-MS** [comment]
Thanks for using Ursgal :)

I will have a look tomorrow, there may be a quick workaround.

Cheers,
JL

**Comment by JB-MS** [comment]
I have changed the code to correctly map these mods for OMSSA.

Could you please check if it works now? Thanks!

A good reference would be the overlap of peptides to the other engines i think.

Cheers,
JL

**Comment by tobymathieson** [comment]
Hi, erm I pulled the new repo but I still get the error. [ WARNING  ]
    The combination of modification name and aminoacid is not supported by
    OMSSA. Continuing without modification: {'composition': {'15N': 1, 'N': 1, 'C': 8, '13C': 4, 'O': 2, 'H': 20}, 'id': '737', 'mass': 229.162932, 'unimod': True, 'org': 'K,fix,any,TMT6plex', 'pos': 'any', '_id': 3, 'aa': 'K', 'name': 'TMT6plex'}

[ WARNING  ]
    The combination of modification name and aminoacid is not supported by
    OMSSA. Continuing without modification: {'composition': {'15N': 1, 'N': 1, 'C': 8, '13C': 4, 'O': 2, 'H': 20}, 'id': '737', 'mass': 229.162932, 'unimod': True, 'org': '*,opt,N-term,TMT6plex', 'pos': 'N-term', '_id': 0, 'aa': '*', 'name': 'TMT6plex'}

am I doing something wrong? Thanks for your quick response!

**Comment by StSchulze** [comment]
Hi,
I tried it with the newest version on samples without TMT labeling, so no idents for that, but I didn't get the error/warning, so for me it seems like it works.

Have you installed ursgal in the python site-packages? If yes, you need to run 'python setup.py install' after pulling the new version ...

**Comment by tobymathieson** [comment]
ah ha, I re installed as instructed and it seems to run without the warning. Will let you know if successful. Thanks for the help so far!

**Comment by JB-MS** [comment]
Does this work now? Can this be closed?

**Comment by tobymathieson** [comment]
Yes, Ursgal now works for TMT with OMSSA. It can be closed. Thanks for your
help
Toby
