### ISSUE TITLE
Time stamps in history and output needs fixing

### ISSUE THREAD

**Issue by fu** [ursgal/ursgal#21]

**Comment by fu** [comment]
Added test_node_execution.py into example_scripts and fixed the _test_node module/wrapper ... 
The test_node_execution.py shows that timestamps are set correctly and history is now correctly reflecting execution times of the node. The general timestamps in the history, i.e. 
"execution",  "postflight" and "preflight" reflect the last engine.

**Comment by JB-MS** [comment]
Solved with commit: 0df29d9c7df49ac9b890839990683d2cb7f0fd80
