### ISSUE TITLE
merge_csvs() should be working if only one file is specified

### ISSUE THREAD

**Issue by StSchulze** [ursgal/ursgal#23]
At the moment the sanity check crashes, because at least two files need to be specified. I think it would be more convenient if it just continues without merging, when only one file is specified, i.e. return the same file.

**Comment by LKremer** [comment]
Should be fixed, you can now specify
1) a list of files (same as before)
2) a list of one file
3) a string (path to a file)
Options 2 and 3 print a warning, skip the whole UNode execution process (including json-dumping etc.) and return the original input file.

The tests are working and I tested all 3 cases in a minimal working example including one downstream UNode. So it should also work with your files, can anyone confirm? In that case the issue can be closed.

**Comment by StSchulze** [comment]
I can confirm, works all fine for me as well, so I'll close it.
Thanks Lukas!
