### ISSUE TITLE
pyahocorasick with Windows and Python3.4+

### ISSUE THREAD

**Issue by JB-MS** [ursgal/ursgal#30]
At the moment, [pyahocorasick](https://github.com/WojciechMula/pyahocorasick) fails to compile/install under Windows (7 and 10 64bit) when using pip with Python3.4+.

Refer to this issue for a (possible/'i-hope-that-it-works-for-you-too') solution: https://github.com/WojciechMula/pyahocorasick/issues/55.

We may have a fix soon, stay tuned.

Cheers,
Johannes

**Comment by biomscholz** [comment]
MS Build tools 2017 failed on my system (10/64 bit) as well (error: some .bat file was not found). Everything worked flawlessly with Build Tools 2015 (on two different systems).

**Comment by fu** [comment]
Work-around: Install windows-bash (under W$10) - everything works flawlessly! Unfortunately, windows does not respect linux file attributes but if one works only on /mnt/c or /mnt/X, i.e. windows native nfs partition, then there is no problem at all 👍

**Comment by JB-MS** [comment]
@StSchulze Python 3.6.3 under Win 7 (additionally installed: Microsoft Visual
C++ Build Tools, http://landinghub.visualstudio.com/visual-cpp-build-tools) works just fine now. I can not test Win 10.

Python3.6 seems to solve also the issue at https://github.com/WojciechMula/pyahocorasick/issues/51

**Comment by fu** [comment]
Can we close this issue ? Maybe add the collected info into the FAQ ?

**Comment by JB-MS** [comment]
I will add it to the FAQ.

**Comment by harsh204016** [comment]
you can  install using conda 

```
conda config --add channels conda-forge
conda install pyahocorasick
```
taken from here https://github.com/conda/conda/issues/5714#issuecomment-567813864
