### ISSUE TITLE
Implement new X!Tandem version ALANINE

### ISSUE THREAD

**Issue by StSchulze** [ursgal/ursgal#35]
A new X!Tandem version is out since february: [http://www.thegpm.org/tandem/](url)
Would be nice to implement it in Ursgal. Although there are no major changes to the normal search, the "expert systems methods for finding PTMs and SAVs" seems to be improved.

**Comment by JB-MS** [comment]
I am already working on it :)

**Comment by JB-MS** [comment]
Implemented now.
