### ISSUE TITLE
install_resources.py not working properly on OS X

### ISSUE THREAD

**Issue by StSchulze** [ursgal/ursgal#36]
After executing

`python install_resources.py`

it all works up to

```
[ -<HTPP>- ] Downloading files from http://www.uni-muenster.de/Biologie.IBBP.AGFufezan/ursgal/resources/darwin/64bit/xtandem_vengeance/xtandem_vengeance.zip ...
```

then it just doesn't go on. Aborting after 10+ minutes results in 

```
[  INFO   ] Please contact the Ursgal team!
                            
[   md5    ] Calculating md5 for xtandem_vengeance.zip ....

    [ WARNING ] md5 of downloaded zip file ursgal/resources/darwin/64bit/xtandem_vengeance/xtandem_vengeance.zip differs from
    [ WARNING ] md5 in knowledge base, exiting now!!!
    [  INFO   ] Please contact the Ursgal team!
                                

[ INFO ] No engines were downloaded, all should be available
```

The tandem_vengeance folder has been created but nothing is downloaded/extracted there.

I'm using OS X Yosemite 10.10.5

**Comment by fu** [comment]
hm, strange works over here (10.11.6)

can you curl it ?

`curl -O http://www.uni-muenster.de/Biologie.IBBP.AGFufezan/ursgal/resources/darwin/64bit/xtandem_vengeance/xtandem_vengeance.zip`

**Comment by StSchulze** [comment]
No, not able to curl it either ...

The folder is empty, nothing downloaded/extracted, so no md5.

Could it be a limitation of the internet connection? But that shouldn't be specific for one file, right?

By the way, same problem for my windows laptop, so it doesn't seem to be OS dependent.

**Comment by fu** [comment]
*merica*

**Comment by fu** [comment]
no just kiddin' :) Let me mail it to you, maybe ?

**Comment by StSchulze** [comment]
Yeah, everything that has vengeance in it's name is forbidden here :P

Sure, would be great but doesn't solve the problem if I'm not the only one that has it!? Although, not sure how likely that is ...

**Comment by StSchulze** [comment]
I will close this for now until this problem occurs for someone else as well ...
