### ISSUE TITLE
setting an unknown parameter should raise an errror/warning

### ISSUE THREAD

**Issue by StSchulze** [ursgal/ursgal#37]
e.g. setting uc.params['new_param_or_incorrect_spelling'] = 'working' should raise an error because 'new_param_or_incorrect_spelling' is not in uparams, at the moment it is accepted and also written into the json but never used, which might be confusing, especially in case of incorrect spelling

**Comment by LKremer** [comment]
I'll look into it when I find the time, maybe there's an elegant way to do this. Do you think it should raise an exception or should it just print a warning and continue with the script?

**Comment by JB-MS** [comment]
Since typos would be the main source of errors, unknown parameters should cause an exit/exception in my opinion, to avoid a silent fail.

**Comment by LKremer** [comment]
Alright, this issue should be resolved.
uc.params is now a subclass of the built-in dict class. The dict-subclass now always checks whether the key is present in uparams and raises an Exception if that's not the case. I also had to whitelist some keys that are not in uparams (e.g. "translations" and some test params).
If you encounter any problems with this, let me know. If not, feel free to close this issue.

**Comment by StSchulze** [comment]
setting an unknown param when the UController is already initialized, e.g.
```
uc = UController()
uc.params['new_param_or_incorrect_spelling'] = 'working'
```
now indeed raises an Exception. However, setting the param during initiallization of the UCotroller, e.g.
```
uc = UController(
    params = {
        'new_param_or_incorrect_spelling' : 'working',
    }
)
```
still works, which should not be the case.

**Comment by LKremer** [comment]
Ah, good catch! Will be fixed.

**Comment by StSchulze** [comment]
Great, works fine, thanks Lukas!
