### ISSUE TITLE
machine_offset_in_ppm

### ISSUE THREAD

**Issue by fu** [ursgal/ursgal#61]
ursgal has a parameter call machine_offset_in_ppm to re-calibrate mgfs. The name suggests that the input should be, e.g. 1 for 1ppm offset. However, the algorithm that uses that parameter, e.g. mzml2mgf expects 1e-6. Any follow up search with an offset of e.g -10 will crash as all mz values will be negative.

**Comment by StSchulze** [comment]
solved with #57
