### ISSUE TITLE
xtandem_version_comparison error

### ISSUE THREAD

**Issue by cguetot** [ursgal/ursgal#82]
Hi,

I just tried to run `xtandem_version_comparison.py`.  However, there is a problem related to the downloading of the fasta file.

I think this is because of the URL on line 58:

`http://www.unimuenster.de/Biologie.IBBP.AGFufezan/misc/Creinhardtii_281_v5_5_CP_MT_with_contaminants_target_decoy.fasta`

best,

carlos

**Comment by StSchulze** [comment]
Hi Carlos,
sorry that it took a bit longer than it should have, but the issue should be fixed with pull request #84 now
