### ISSUE TITLE
unifycsv fails for nonspecific and semi_trypsin

### ISSUE THREAD

**Issue by cguetot** [ursgal/ursgal#94]
Hi, 

I am trying to run XTandem using semi_tryptic and nonspecific parameters. However, `unifycsv` fails all the time.  This is one of my outputs with nonspecific:
 

> [ profile  ] Initializing profile QExactive+
[ profile  ] 2 parameters have been updated
[  prprun  ] Preparing unode run for engine xtandem_alanine on file(s) CK_H1801_324.mgf
[ set_ios  ] Setting self.io["input"]
[   Info   ] Generated engine xtandem_alanine output file name: /data/DDA_ursgal/ursgal_dda/xtandem_alanine/CK_H1801_324_xtandem_alanine.xml.gz
[   Info   ] Skipping search_mgf() on file CK_H1801_324.mgf since it was previously executed with the same input file(s) and parameters.
[   Info   ] To re-run, use search_mgf( force=True )
[ dmpjson  ] Preparing json dump
[ dmpjson  ] Json dumped. Path: /data/DDA_ursgal/ursgal_dda/xtandem_alanine/CK_H1801_324_xtandem_alanine.xml.gz.u.json
[ profile  ] Initializing profile QExactive+
[ profile  ] 2 parameters have been updated
[  prprun  ] Preparing unode run for engine xtandem2csv_1_0_0 on file(s) /data/DDA_ursgal/ursgal_dda/xtandem_alanine/CK_H1801_324_xtandem_alanine.xml.gz
[ set_ios  ] Setting self.io["input"]
[   Info   ] Generated engine xtandem2csv_1_0_0 output file name: /data/DDA_ursgal/ursgal_dda/xtandem_alanine/CK_H1801_324_xtandem_alanine.csv
[   Info   ] Skipping execute_unode() on file CK_H1801_324_xtandem_alanine.xml.gz since it was previously executed with the same input file(s) and parameters.
[   Info   ] To re-run, use execute_unode( force=True )
[ dmpjson  ] Preparing json dump
[ dmpjson  ] Json dumped. Path: /data/DDA_ursgal/ursgal_dda/xtandem_alanine/CK_H1801_324_xtandem_alanine.csv.u.json
[ profile  ] Initializing profile QExactive+
[ profile  ] 2 parameters have been updated
[  prprun  ] Preparing unode run for engine upeptide_mapper_1_0_0 on file(s) /data/DDA_ursgal/ursgal_dda/xtandem_alanine/CK_H1801_324_xtandem_alanine.csv
[ set_ios  ] Setting self.io["input"]
[   Info   ] Generated engine upeptide_mapper_1_0_0 output file name: /data/DDA_ursgal/ursgal_dda/xtandem_alanine/CK_H1801_324_xtandem_alanine_pmap.csv
[   Info   ] Skipping execute_unode() on file CK_H1801_324_xtandem_alanine.csv since it was previously executed with the same input file(s) and parameters.
[   Info   ] To re-run, use execute_unode( force=True )
[ dmpjson  ] Preparing json dump
[ dmpjson  ] Json dumped. Path: /data/DDA_ursgal/ursgal_dda/xtandem_alanine/CK_H1801_324_xtandem_alanine_pmap.csv.u.json
[ profile  ] Initializing profile QExactive+
[ profile  ] 2 parameters have been updated
[  prprun  ] Preparing unode run for engine unify_csv_1_0_0 on file(s) /data/DDA_ursgal/ursgal_dda/xtandem_alanine/CK_H1801_324_xtandem_alanine_pmap.csv
[ set_ios  ] Setting self.io["input"]
[   Info   ] Generated engine unify_csv_1_0_0 output file name: /data/DDA_ursgal/ursgal_dda/xtandem_alanine/CK_H1801_324_xtandem_alanine_pmap_unified.csv
[   Info   ] execute_unode() scheduled on input file CK_H1801_324_xtandem_alanine_pmap.csv
[   Info   ] Reason for run: parameter "keep_asp_pro_broken_peps" was not found in previous output params....
 & Previous run was not completed, status launching
[ dmpjson  ] Preparing json dump
[ dmpjson  ] Json dumped. Path: /data/DDA_ursgal/ursgal_dda/xtandem_alanine/CK_H1801_324_xtandem_alanine_pmap_unified.csv.u.json

        -\-     unify_csv_1_0_0 run initialized with CK_H1801_324_xtandem_alanine_pmap.csv (Wed Nov 28 08:38:57 2018)     -/-

[   run    ] Preparing engine
[   run    ] Starting engine
[ Citation ] 
[  Please  ] 
[  cite:   ] Kremer, L. P. M., Leufken, J., Oyunchimeg, P., Schulze, S. & Fufezan, C. (2016) Ursgal, Universal Python Module Combining Common Bottom-Up Proteomics Tools for Large-Scale Analysis. J. Proteome res. 15, 788-794.
[  -----   ] 
[ Citation ] 
[ PREFLGHT ] Executing preflight sequence ...
[ prefligh ] Execution time 0.000 seconds
[ -ENGINE- ] Executing conversion ..

[ unifycsv ] Converting CK_H1801_324_xtandem_alanine_pmap.csv of engine xtandem_alanine to unified CSV format...
        
[ unify_cs ] Buffering csv file
[ unify_cs ] Buffering csv file done
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-92-065cfb4bf70b> in <module>
      8             input_file=mgf_file,
      9             engine='xtandem_alanine',
---> 10             force=Force
     11         )
     12 

/data/external/installers/ursgal/env/lib/python3.6/site-packages/ursgal/ucontroller.py in search(self, input_file, engine, force, output_file_name)
   1889             engine           = self.params['unify_csv_converter_version'],
   1890             force            = force,
-> 1891             merge_duplicates = True,
   1892         )
   1893         return unified_search_results

/data/external/installers/ursgal/env/lib/python3.6/site-packages/ursgal/ucontroller.py in execute_misc_engine(self, input_file, engine, force, output_file_name, merge_duplicates)
    962                 force            = force,
    963                 output_file_name = output_file_name,
--> 964                 merge_duplicates = merge_duplicates,
    965             )
    966 

/data/external/installers/ursgal/env/lib/python3.6/site-packages/ursgal/ucontroller.py in execute_unode(self, input_file, engine, force, output_file_name, dry_run, merge_duplicates)
   2927         report = self.run_unode_if_required(
   2928             force, engine_name, answer,
-> 2929             merge_duplicates=merge_duplicates
   2930         )
   2931         return report['output_file']

/data/external/installers/ursgal/env/lib/python3.6/site-packages/ursgal/ucontroller.py in run_unode_if_required(self, force, engine_name, answer, merge_duplicates, history_addon)
   2184             json_path = self.dump_json_and_calc_md5()
   2185             report = self.unodes[ engine_name ]['class'].run(
-> 2186                 json_path = json_path,
   2187             )
   2188 

/data/external/installers/ursgal/env/lib/python3.6/site-packages/ursgal/unode.py in run(self, json_path)
   1398         )
   1399         report['preflight'] = self._preflight()
-> 1400         report['execution'] = self._execute()
   1401         report['postflight'] = self._postflight()
   1402 

/data/external/installers/ursgal/env/lib/python3.6/site-packages/ursgal/wrappers/unify_csv_1_0_0.py in _execute(self)
     91             params          = self.params,
     92             search_engine   = last_engine,
---> 93             score_colname   = last_search_engine_colname,
     94         )
     95         for tmp_file in tmp_files:

/data/external/installers/ursgal/env/lib/python3.6/site-packages/ursgal/resources/platform_independent/arc_independent/unify_csv_1_0_0/unify_csv_1_0_0.py in main(input_file, output_file, scan_rt_lookup, params, search_engine, score_colname)
   1013                             )
   1014                             missed_cleavage_counter += \
-> 1015                                 len(re.findall(missed_cleavage_pattern, line_dict['Sequence']))
   1016                         elif cleavage_site == 'N':
   1017                             missed_cleavage_pattern = '[^{1}]{0}'.format(

/usr/lib/python3.6/re.py in findall(pattern, string, flags)
    220 
    221     Empty matches are included in the result."""
--> 222     return _compile(pattern, flags).findall(string)
    223 
    224 def finditer(pattern, string, flags=0):

/usr/lib/python3.6/re.py in _compile(pattern, flags)
    299     if not sre_compile.isstring(pattern):
    300         raise TypeError("first argument must be string or compiled pattern")
--> 301     p = sre_compile.compile(pattern, flags)
    302     if not (flags & DEBUG):
    303         if len(_cache) >= _MAXCACHE:

/usr/lib/python3.6/sre_compile.py in compile(p, flags)
    560     if isstring(p):
    561         pattern = p
--> 562         p = sre_parse.parse(p, flags)
    563     else:
    564         pattern = None

/usr/lib/python3.6/sre_parse.py in parse(str, flags, pattern)
    853 
    854     try:
--> 855         p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
    856     except Verbose:
    857         # the VERBOSE flag was switched on inside the pattern.  to be

/usr/lib/python3.6/sre_parse.py in _parse_sub(source, state, verbose, nested)
    414     while True:
    415         itemsappend(_parse(source, state, verbose, nested + 1,
--> 416                            not nested and not items))
    417         if not sourcematch("|"):
    418             break

/usr/lib/python3.6/sre_parse.py in _parse(source, state, verbose, nested, first)
    521                 if this is None:
    522                     raise source.error("unterminated character set",
--> 523                                        source.tell() - here)
    524                 if this == "]" and set != start:
    525                     break

error: unterminated character set at position 1

unify_csv_1_0_0 

> ``

>

**Comment by StSchulze** [comment]
Hi Carlos,

the 'nonspecific' enzyme option had not been included in the uparams uvalue_translation for unify_csv (and some others) yet, therefore it could not handle that case. In general, we have not included all possible enzymes and combinations for all engines, since this would be a lot (and not every engine can handle every enzyme/combination). So whenever you don't find the enzyme/combination that you have used, just include it in uparams['enzyme']['uvalue_translation'] (while making sure that the corresponding engine can actually handle it).
I have included it in the most recent pull request (#95) and tested it without any obvious problems - let me know if that works for you as well.

Regarding the semi tryptic search, this seems a bit strange to me. I have done semi enzymatic searches before without any issues. How did you specify it? The way it should be done is to use the corresponding enzyme for the uparam "enzyme", i.e. in your case "trypsin", and then set the uparam "semi_enzyme" to True. Let me know if that causes an error for you (and if so, which one).

Best,
Stefan

**Comment by cguetot** [comment]
Thanks for your quick reply. I updated to the lastest version to include your changes. Unfortunately, the problem is still there; I used `xtandem_alanine` with the `enzyme` parameter 'nonspecific' and 'semi_tryptic'.  In both cases, an error message raises when `unifycsv` try to convert to unified CSV format.  I will attach both logs:

## nonspecific

> [ unifycsv ] Converting nonspecific_Emma_M1811_058_xtandem_alanine_pmap.csv of engine xtandem_alanine to uni                                   fied CSV format...
> 
> [ unify_cs ] Buffering csv file
> [ unify_cs ] Buffering csv file done
> Traceback (most recent call last):r: 0/45091
>   File "dda_custom_nonspecific.py", line 280, in <module>
>     ddar = run_single_mgf_dda_search(mzML_file, search_params)
>   File "dda_custom_nonspecific.py", line 256, in run_single_mgf_dda_search
>     dda_results = dda_searches(mgf_file, uc)
>   File "dda_custom_nonspecific.py", line 177, in dda_searches
>     force=Force
>   File "/usr/local/lib/python3.6/dist-packages/ursgal/ucontroller.py", line 1891, in search
>     merge_duplicates = True,
>   File "/usr/local/lib/python3.6/dist-packages/ursgal/ucontroller.py", line 964, in execute_misc_engine
>     merge_duplicates = merge_duplicates,
>   File "/usr/local/lib/python3.6/dist-packages/ursgal/ucontroller.py", line 2929, in execute_unode
>     merge_duplicates=merge_duplicates
>   File "/usr/local/lib/python3.6/dist-packages/ursgal/ucontroller.py", line 2186, in run_unode_if_required
>     json_path = json_path,
>   File "/usr/local/lib/python3.6/dist-packages/ursgal/unode.py", line 1400, in run
>     report['execution'] = self._execute()
>   File "/usr/local/lib/python3.6/dist-packages/ursgal/wrappers/unify_csv_1_0_0.py", line 93, in _execute
>     score_colname   = last_search_engine_colname,
>   File "/usr/local/lib/python3.6/dist-packages/ursgal/resources/platform_independent/arc_independent/unify_c                                   sv_1_0_0/unify_csv_1_0_0.py", line 1015, in main
>     len(re.findall(missed_cleavage_pattern, line_dict['Sequence']))
>   File "/usr/lib/python3.6/re.py", line 222, in findall
>     return _compile(pattern, flags).findall(string)
>   File "/usr/lib/python3.6/re.py", line 301, in _compile
>     p = sre_compile.compile(pattern, flags)
>   File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
>     p = sre_parse.parse(p, flags)
>   File "/usr/lib/python3.6/sre_parse.py", line 855, in parse
>     p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
>   File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
>     not nested and not items))
>   File "/usr/lib/python3.6/sre_parse.py", line 523, in _parse
>     source.tell() - here)
> sre_constants.error: unterminated character set at position 1
> 

## semi_tryptic

> [ unifycsv ] Converting semi_tryptic_Emma_M1811_058_xtandem_alanine_pmap.csv of engine xtandem_alanine to unified CSV format...
> 
> Traceback (most recent call last):
>   File "dda_custom_semitryptic.py", line 281, in <module>
>     ddar = run_single_mgf_dda_search(mzML_file, search_params)
>   File "dda_custom_semitryptic.py", line 257, in run_single_mgf_dda_search
>     dda_results = dda_searches(mgf_file, uc)
>   File "dda_custom_semitryptic.py", line 178, in dda_searches
>     force=Force
>   File "/usr/local/lib/python3.6/dist-packages/ursgal/ucontroller.py", line 1891, in search
>     merge_duplicates = True,
>   File "/usr/local/lib/python3.6/dist-packages/ursgal/ucontroller.py", line 964, in execute_misc_engine
>     merge_duplicates = merge_duplicates,
>   File "/usr/local/lib/python3.6/dist-packages/ursgal/ucontroller.py", line 2929, in execute_unode
>     merge_duplicates=merge_duplicates
>   File "/usr/local/lib/python3.6/dist-packages/ursgal/ucontroller.py", line 2186, in run_unode_if_required
>     json_path = json_path,
>   File "/usr/local/lib/python3.6/dist-packages/ursgal/unode.py", line 1400, in run
>     report['execution'] = self._execute()
>   File "/usr/local/lib/python3.6/dist-packages/ursgal/wrappers/unify_csv_1_0_0.py", line 93, in _execute
>     score_colname   = last_search_engine_colname,
>   File "/usr/local/lib/python3.6/dist-packages/ursgal/resources/platform_independent/arc_independent/unify_csv_1_0_0/unify_csv_1_0_0.py", line 283, in main
>     allowed_aa, cleavage_site, inhibitor_aa = params['translations']['enzyme'].split(';')
> ValueError: not enough values to unpack (expected 3, got 1)
>

**Comment by StSchulze** [comment]
> I updated to the lastest version to include your changes.

Does that mean you pulled the latest master branch or you pulled my pull request? It's not merged into the master yet, so you need to checkout my pull request to test the changes.

Regarding semi_tryptic, semi-enzymatic cleavages are not defined within the "enzyme" parameter, as I tried to explain above, so just using "semi_tryptic" for "enzyme" will not work. Here is how you would need to define it:
```
params = {
    "enzyme": "trypsin",
    "semi_enzyme": True,
}
```

**Comment by cguetot** [comment]
Dear StSchulze,

It looks like it work.  However, I am trying to follow the instructions above to do the same with **aspn**.  I am failling so far.  Can you help with this one?

thanks in advance,

**Comment by StSchulze** [comment]
Hi Carlos,
glad to hear that it works, will merge it into the master soon then.
Could you explain a bit more what you are struggeling with for "aspn"? "aspn" is included for most of the engines, including unify_csv, so it should be working to just specify it as enzyme!?

**Comment by cguetot** [comment]
Hi  StSchulze, 
Sorry for taking so long, I was testing in more detail.  When the param "semi_enzyme"  is set to true and combined with trypsin or aspn, sometimes (no all of them) msfgplus creates columns with two values separated by semicolon. for example, I got several rows in the field MS-GF:SpecEValue like this 5.131911E-7;1.4088748E-8.  The same happens with MS-GF:RawScore and MS-GF:EValue.

Given that say, this leds to error message in the posterior validation process with percolator or qvality.
[semi_sample.zip](https://github.com/ursgal/ursgal/files/2679460/semi_sample.zip)

**Comment by StSchulze** [comment]
Since the modifications seem to solve the problem in regard to the enzyme, I have merged the pull request and close this issue here.
For the question in regard to merged rows (and consequently failing validation engines), I opened a new issue.
