### ISSUE TITLE
Incorrect merging of duplicate rows

### ISSUE THREAD

**Issue by StSchulze** [ursgal/ursgal#97]
Hi StSchulze,
Sorry for taking so long, I was testing in more detail.  When the param "semi_enzyme"  is set to true and combined with trypsin or aspn, sometimes (no all of them) msfgplus creates columns with two values separated by semicolon. for example, I got several rows in the field MS-GF:SpecEValue like this 5.131911E-7;1.4088748E-8.  The same happens with MS-GF:RawScore and MS-GF:EValue.

Given that say, this leds to error message in the posterior validation process with percolator or qvality.
[semi_sample.zip](https://github.com/ursgal/ursgal/files/2679460/semi_sample.zip)

_Originally posted by @cguetot in https://github.com/ursgal/ursgal/issues/94#issuecomment-447272943_

**Comment by StSchulze** [comment]
Hi Carlos,
since this is a slightly different topic, I have moved it to a new issue.
This problem originates from the fact that duplicate rows are merged at the end of unify_csv (at least when using the ucontroller search() function). Duplicate rows are defined as rows with the same PSM (defined by uparam['psm_defining_colnames']) and are then merged into one row. So the question here would be: why does MS-GF+ give different scores to the same PSM?
In order to try to answer that, could you upload the corresponding MS-GF+ result file(s) as well (not the unified file, but the one before that, or even before the peptide mapping)?

As an easy workaround, you could also set "merge_duplicates" to False when executing unify_csv (i.e. `uc.execute_misc_engine(input_file=<your_file>, engine='unify_csv', merge_duplicates=False)`). This should prevent the error in qvality, however, depending on how many of those duplicate PSMs you have, this might effect the statistical processing done with qvality.

**Comment by StSchulze** [comment]
@cguetot: does this problem still occur? If you need further help with it, the original output files before the merging would be useful to find the problem.

**Comment by cguetot** [comment]
> @cguetot: does this problem still occur? If you need further help with it, the original output files before the merging would be useful to find the problem.

After testing with more than 50 runs, I found that setting `semi = True` or running nonspecific search can lead to the mentioned problem.  It is solved after setting `merge_duplicates` to `False` in the `mapped_csv_search_results` (`ucontroller.py`) in the `search` method.

**Comment by StSchulze** [comment]
The latest version of MS-GF+ has been implemented now.
It includes a fix for an issue that resulted in duplicated entries (https://github.com/MSGFPlus/msgfplus/issues/49). I'm not sure if this is the same problem or not, but it could be worth a try.

**Comment by cguetot** [comment]
Hi,
I will run some tests with this new version.
Tack!

**Comment by cguetot** [comment]
The problem seems to be solved with the pull/114.

**Comment by StSchulze** [comment]
Thanks Carlos for checking (and reporting in the first place)
